/**
 * FerroUI Design Tokens
<<<<<<< HEAD
 * 
 * This file is a placeholder for TypeDoc discovery. 
 * The actual tokens are generated by scripts/build-tokens.ts into dist/tokens.ts.
 */

export * from '../dist/tokens.js';
=======
 *
 * This file is a placeholder for TypeDoc discovery.
 * The actual tokens are generated by scripts/build-tokens.ts into dist/tokens.ts.
 */

export * from "../dist/tokens.js";
>>>>>>> 35868da (chore: final cleanup and enterprise alignment)
